# Generated by Django 6.0.1 on 2026-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=60, unique=True)),
                ('desc', models.CharField(blank=True, default='No Description Provided', max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Food',
            },
        ),
    ]
