# Generated by Django 6.0.1 on 2026-01-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmodel',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Food'},
        ),
    ]
