# Generated by Django 6.0.1 on 2026-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodmodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
