# Generated by Django 6.0.1 on 2026-03-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
