# Generated by Django 6.0.1 on 2026-02-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
