# Generated by Django 6.0.1 on 2026-03-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
