# Generated by Django 6.0.1 on 2026-03-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='price',
        ),
    ]
